name: ss5401
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=4.2.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - arrow-cpp=11.0.0=ha770c72_42_cpu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=23.1.0=py312h06a4308_0
  - aws-c-auth=0.7.4=h1083cbe_2
  - aws-c-cal=0.6.2=h09139f6_2
  - aws-c-common=0.9.3=hd590300_0
  - aws-c-compression=0.2.17=h184a658_3
  - aws-c-event-stream=0.3.2=h6fea174_2
  - aws-c-http=0.7.13=hb59894b_2
  - aws-c-io=0.13.33=h161b759_0
  - aws-c-mqtt=0.9.7=h55cd26b_0
  - aws-c-s3=0.3.17=hfb4bb88_4
  - aws-c-sdkutils=0.1.12=h184a658_2
  - aws-checksums=0.1.17=h184a658_2
  - aws-crt-cpp=0.24.2=ha28989d_2
  - aws-sdk-cpp=1.11.156=h314d761_4
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.2=py312h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.5=h0f2a231_0
  - bokeh=3.3.4=py312he106c6f_0
  - boost-cpp=1.84.0=h44aadfe_1
  - bottleneck=1.3.5=py312ha883a20_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cartopy=0.22.0=py312h526ad5a_0
  - cdsapi=0.6.1=pyhd8ed1ab_0
  - certifi=2024.2.2=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_0
  - cfgrib=0.9.10.4=pyhd8ed1ab_0
  - cftime=1.6.2=py312ha883a20_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=py312h06a4308_0
  - cloudpickle=2.2.1=py312h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.2=py312h5eee18b_0
  - dask=2023.11.0=py312h06a4308_0
  - dask-core=2023.11.0=py312h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2023.11.0=py312h06a4308_0
  - eccodes=2.32.1=h35c6de3_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - findlibs=0.0.5=pyhd8ed1ab_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=py312h06a4308_0
  - geos=3.8.0=he6710b0_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.6.0=h6f12383_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py312h06a4308_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.3=nompi_h4f84152_100
  - heapdict=1.0.1=pyhd3eb1b0_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.26.0=py312h06a4308_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=py312h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py312h06a4308_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.28.0=py312h06a4308_0
  - ipython=8.20.0=py312h06a4308_0
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jasper=4.0.0=h0ff4b12_0
  - jedi=0.18.1=py312h06a4308_1
  - jinja2=3.1.3=py312h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.5.0=py312h06a4308_0
  - jupyter_events=0.8.0=py312h06a4308_0
  - jupyter_server=2.10.0=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.1.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312h06a4308_0
  - jupyterlab_widgets=3.0.9=py312h06a4308_0
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h295c915_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libarrow=11.0.0=h75f0d2f_42_cpu
  - libboost=1.84.0=h8013b2b_1
  - libboost-devel=1.84.0=h00ab1b0_1
  - libboost-headers=1.84.0=ha770c72_1
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hdc74915_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.12.0=h19a6dae_3
  - libgrpc=1.58.1=h30d5116_0
  - libiconv=1.17=hd590300_2
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.24.3=hf27288f_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.4.0=hecacb30_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.5=h232c23b_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - locket=1.0.0=py312h06a4308_0
  - lz4=4.3.2=py312h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.8.0=py312h06a4308_0
  - matplotlib-base=3.8.0=py312h526ad5a_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - msgpack-python=1.0.3=py312hdb19cb5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.10.0=py312h06a4308_0
  - nbformat=5.9.2=py312h06a4308_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.6.0=py312h06a4308_0
  - netcdf4=1.6.5=nompi_py312h26027e0_100
  - notebook=7.1.1=pyhd8ed1ab_0
  - notebook-shim=0.2.3=py312h06a4308_0
  - numexpr=2.8.7=py312he7dcb8a_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.1=hd590300_0
  - orc=1.9.0=h208142c_3
  - overrides=7.4.0=py312h06a4308_0
  - packaging=23.1=py312h06a4308_0
  - pandas=2.1.4=py312h526ad5a_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py312h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.2.0=py312h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - ply=3.11=py312h06a4308_1
  - proj=9.3.1=he5811b7_0
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py312hb107042_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pyparsing=3.0.9=py312h06a4308_0
  - pyproj=3.6.1=py312h6268720_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pyshp=2.3.1=py312h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.0=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-eccodes=1.7.0=py312hc7c0aa3_0
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-lmdb=1.4.1=py312h6a678d5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=4_cp312
  - pytz=2023.3.post1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole-base=5.5.1=pyha770c72_0
  - qtpy=2.4.1=py312h06a4308_0
  - rdma-core=50.0=hd3aeb46_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - s2n=1.3.54=h06160fa_0
  - scipy=1.11.4=py312h2809609_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=69.1.1=pyhd8ed1ab_0
  - shapely=2.0.1=py312h1789038_1
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.0=py312h06a4308_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py312h06a4308_1
  - toolz=0.12.0=py312h06a4308_0
  - tornado=6.3.3=py312h5eee18b_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.7.1=py312h06a4308_0
  - typing-extensions=4.9.0=py312h06a4308_1
  - typing_extensions=4.9.0=py312h06a4308_1
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=h75e419f_3
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=0.58.0=py312h06a4308_4
  - wheel=0.42.0=pyhd8ed1ab_0
  - widgetsnbextension=3.5.1=pyh9f0ad1d_3
  - xarray=2023.6.0=py312h06a4308_0
  - xkeyboard-config=2.41=hd590300_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xyzservices=2022.9.0=py312h06a4308_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=py312h06a4308_0
  - zipp=3.17.0=py312h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - coverage==6.5.0
      - coveralls==3.3.1
      - docopt==0.6.2
prefix: /home/talfan/anaconda3/envs/ss5401
